global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@prometheus-server.com'
#Above global values can be used by any receiver
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: 'critical'
      receiver: discord
#Example filtering
    - match:
        team: global-infra
      receiver: global-infra-email
    - match:
        team: internal-infra
      receiver: internal-infra-email
#
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'discord'
    slack_configs:
      - api_url: 'https://discord.com/api/webhooks/xxxxxxxx/slack' #add /slack at the end.
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
        color: "#ff0000"
        send_resolved: true
#receivers for example filtering above
  - name: global-infra-email
    email_configs:
      - to: "root@prometheus-server.com"
        require_tls: false
  - name: internal-infra-email
    email_configs:
      - to: "admin@prometheus-server.com"
        require_tls: false
#
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']